package serv

import (
	"bytes"
	"strings"
	"time"

	"github.com/JellyTony/goim"
	"github.com/JellyTony/goim/container"
	wire "github.com/JellyTony/goim/pkg"
	"github.com/JellyTony/goim/pkg/logger"
	"github.com/JellyTony/goim/pkg/pkt"
	"google.golang.org/protobuf/proto"
)

var log = logger.WithFields(logger.Fields{
	"service": wire.SNChat,
	"pkg":     "serv",
})

// ServHandler ServHandler
type ServHandler struct {
	r          *goim.Router
	cache      goim.SessionStorage
	dispatcher *ServerDispatcher
}

// Accept this connection
func (h *ServHandler) Accept(conn goim.Conn, timeout time.Duration) (string, goim.Metadata, error) {
	_ = conn.SetReadDeadline(time.Now().Add(timeout))
	frame, err := conn.ReadFrame()
	if err != nil {
		return "", nil, err
	}

	var req pkt.InnerHandshakeReq
	err = proto.Unmarshal(frame.GetPayload(), &req)
	if err != nil {
		return "", nil, err
	}

	log.Info("Accept -- ", req.ServiceId)
	return req.ServiceId, nil, nil
}

func (h *ServHandler) Receive(ag goim.Agent, payload []byte) {
	buf := bytes.NewBuffer(payload)
	packet, err := pkt.MustReadLogicPkt(buf)
	if err != nil {
		return
	}
	var session *pkt.Session
	if packet.Command == wire.CommandLoginSignIn {
		server, _ := packet.GetMeta(wire.MetaDestServer)
		session = &pkt.Session{
			ChannelId: packet.ChannelId,
			GateId:    server.(string),
			Tags:      []string{"AutoGenerated"},
		}
	} else {
		// TODO：优化点
		session, err = h.cache.Get(packet.ChannelId)
		if err == goim.ErrSessionNil {
			_ = RespErr(ag, packet, pkt.Status_SessionNotFound)
			return
		} else if err != nil {
			_ = RespErr(ag, packet, pkt.Status_SystemException)
			return
		}
	}

	logger.Debugf("receive a message from %s  %s", session, &packet.Header)
	err = h.r.Serve(packet, h.dispatcher, h.cache, session)
	if err != nil {
		log.Warn(err)
	}
}

func RespErr(ag goim.Agent, p *pkt.LogicPkt, status pkt.Status) error {
	packet := pkt.NewFrom(&p.Header)
	packet.Status = status
	packet.Flag = pkt.Flag_Response

	p.AddStringMeta(wire.MetaDestChannels, p.Header.ChannelId)
	return container.Push(ag.ID(), p)
}

type ServerDispatcher struct{}

func (d *ServerDispatcher) Push(gateway string, channels []string, p *pkt.LogicPkt) error {
	p.AddStringMeta(wire.MetaDestChannels, strings.Join(channels, ","))
	return container.Push(gateway, p)
}

// Disconnect default listener
func (h *ServHandler) Disconnect(id string) error {
	logger.Warnf("close event of %s", id)
	return nil
}
